name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
      - name: Upload blob report to GitHub Actions Artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: ortoni-report-${{ matrix.shardIndex }}
          path: ortoni-report
          retention-days: 1

  merge-shards:
    needs: playwright-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Download shard reports
        uses: actions/download-artifact@v4
        with:
          name: ortoni-report-1
          path: ortoni-report/1
      - uses: actions/download-artifact@v4
        with:
          name: ortoni-report-2
          path: ortoni-report/2
      - uses: actions/download-artifact@v4
        with:
          name: ortoni-report-3
          path: ortoni-report/3
      - uses: actions/download-artifact@v4
        with:
          name: ortoni-report-4
          path: ortoni-report/4
      - name: Merge shard reports
        run: npx ortoni-report merge-shards
