name: Playwright Tests with Ortoni Report

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests (shard ${{ matrix.shardIndex }}/${{ matrix.shardTotal }})
        run: npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}

      - name: Upload shard report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: ortoni-report-${{ matrix.shardIndex }}
          path: ortoni-report
          retention-days: 1

  merge-shards:
    needs: playwright-tests
    runs-on: ubuntu-latest
    if: always() # run even if shards failed
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Prepare ortoni-report folder
        run: rm -rf ortoni-report && mkdir ortoni-report

      - name: Download all shard reports
        run: |
          for i in 1 2 3 4; do
            echo "Downloading shard $i..."
            gh run download --name "ortoni-report-$i" --dir ortoni-report || true
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge reports
        run: npx ortoni-report merge-report

      - name: Upload merged report
        uses: actions/upload-artifact@v4
        with:
          name: ortoni-report
          path: ortoni-report
          retention-days: 7

      - name: Deploy merged report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ortoni-report
          force_orphan: true
